required = [
  "github.com/bazelbuild/bazel-gazelle/cmd/gazelle",
]

[prune]
  unused-packages = true
  go-tests = true
  non-go = true

[[constraint]]
  branch = "master"
  name = "github.com/golang/glog"

[[constraint]]
  branch = "master"
  name = "golang.org/x/build"


# BEGIN gazelle dependencies
# Based on https://github.com/bazelbuild/bazel-gazelle/blob/0.10.1/deps.bzl

[[constraint]]
  name = "github.com/bazelbuild/bazel-gazelle"
  version = "0.14.0"

[[constraint]]
  name = "github.com/bazelbuild/buildtools"
  version = "0.15.0"

# END gazelle dependencies
